name: pr-check-code

on: pull_request

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}

jobs:
  npm-build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - run: npm ci

      - run: npm test

  schema-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - name: Check checkout subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: checkout
          schema: ./subgraphs/checkout/schema.graphql

      - name: Check discovery subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: discovery
          schema: ./subgraphs/discovery/schema.graphql

      - name: Check inventory subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: inventory
          schema: ./subgraphs/inventory/schema.graphql

      - name: Check orders subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: orders
          schema: ./subgraphs/orders/schema.graphql

      - name: Check products subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: products
          schema: ./subgraphs/products/schema.graphql

      - name: Check reviews subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: reviews
          schema: ./subgraphs/reviews/schema.graphql

      - name: Check shipping subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: shipping
          schema: ./subgraphs/shipping/schema.graphql

      - name: Check users subgraph
        uses: apollosolutions/rover-actions/subgraph-check@v1
        with:
          apollo-key: ${{ secrets.APOLLO_KEY }}
          graph-ref: ${{ vars.APOLLO_GRAPH_REF }}
          name: users
          schema: ./subgraphs/users/schema.graphql

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
